---
- name: Install Kernel Devel for RedHat OS family
  yum:
    name: "kernel-devel-{{ ansible_kernel }}"
    state: latest

- name: Ensure sysdig repo for RedHat OS family exists
  template:
    src: sysdig.repo.j2
    dest: /etc/yum.repos.d/sysdig.repo
    mode: 0644
    owner: root
    group: root
    force: "yes"
...
